# Generated by Django 3.2 on 2021-10-13 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.DateTimeField(auto_created=True)),
                ('on_bot_name', models.CharField(default='Anonymous', max_length=255)),
                ('tg_id', models.CharField(max_length=255, unique=True)),
                ('invite_number', models.IntegerField(default=0)),
                ('last_user', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_talk', models.CharField(default='', max_length=255)),
                ('blocks', models.ManyToManyField(related_name='_main_user_blocks_+', to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='Error', max_length=255)),
                ('taken_time', models.DateTimeField(auto_now_add=True)),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.user')),
            ],
        ),
    ]
